### PR TITLE
Merge develop to master for 1.23 release

### PR DESCRIPTION
**Pull request by taojing2002**

### CODE REVIEW

**Comment by mbjones** [comment]
I checked validity of the xml file with: 

```sh
$ xml val -s http://ns.dataone.org/service/types/v2.0 --err objectFormatListV2.xml
objectFormatListV2.xml - valid
```
Looks good 🎉

**Review by mbjones — APPROVED** [review]
@twhiteaker @srearl @taojing2002 @datadavev @amoeba @csjx I've looked this over and it looks good to me, and is ready for release.  The file validates with xmlstarlet. I think the release is ready to go. We can handle the rest of the proposed format additions in another release so that these get into production.

**Comment by twhiteaker** [comment]
I'd like to get CodeMeta, GeoJSON, File GDB, the edits to R Markdown, and GeoPackage in there soon as well.  It looks like most of those still need some discussion, but CodeMeta seems straightforward.  Regardless, I'm grateful that this repo is active!

**Comment by amoeba** [comment]
Looks good to me, @mbjones

**Comment by mbjones** [comment]
Seeing no objections, I updated the README with the new version number, and am merging this PR to master for v1.23 release. @taojing2002 please include v1.23 in the DataONE formats service at your earliest convenience. Thanks to everyone for the contributions, especially @twhiteaker !

**Comment by taojing2002** [comment]
I have deployed it to production, stage, stage-2, sandbox and sandbox2.
https://cn.dataone.org/cn/v2/formats

**Pull request merged**
