### PR TITLE
release changes for version 1.26

### PR DESCRIPTION
**Pull request by mbjones**
Release changes for v 1.26 proposed:

- Geopackage #14
- GeoDatabase #15 
- GeoJSON #16 
- NetCDF CF versions 1.5-1.8 #17 
- RMarkdown and Markdown name changes #18

### CODE REVIEW

**Comment by mbjones** [comment]
Ready for review for v 1.26 of the object formats. Please put comments here, or if there is a large change needed for one of the proposed changes, please reopen the associated ticket listed above.

**Comment by mbjones** [comment]
@twhiteaker let me know if this all looks good to you, seeing as you proposed most of these changes. Thanks!

**Comment by twhiteaker** [comment]
@mbjones I reviewed the changes and they look good to me.  Thanks for incorporating these types.

**Review by datadavev — APPROVED** [review]

**Review by csjx — APPROVED** [review]
LGTM

**Pull request merged**
